### ISSUE TITLE
Cannot resolve dependencies of ClsModule 

### ISSUE THREAD

**Issue by linardsblk** [Papooch/nestjs-cls#77] opened 2023-07-07 09:02 UTC
Hi, after implementing ClsModule within my application, I get this dependency error and I am unsure on how to fix. Does anyone have any guidance?

```
[Nest] 66508  - 07/07/2023, 11:57:53 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context.

Potential solutions:
- Is ClsModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current ClsModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within ClsModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

Error: Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context.

Potential solutions:
- Is ClsModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current ClsModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within ClsModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:248:19)
    at Injector.resolveComponentInstance (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:202:33)
    at resolveParam (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:123:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:138:27)
    at Injector.loadInstance (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:64:13)
    at Injector.loadProvider (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/injector.js:91:9)
    at /Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 0)
    at InstanceLoader.createInstancesOfProviders (/Users/linards/Documents/projects/fripro/apps/server/node_modules/@nestjs/core/injector/instance-loader.js:55:9)

```    
    
    

I implemented it just like in docs by adding module to AppModule imports

```
ClsModule.forRoot({
      global: true,
      middleware: { mount: true },
    }),
    ```

**Comment by Papooch** [comment] 2023-07-07 17:49
Are you by chance consuming it via a custom npm package?

**Comment by AvnerMaster** [comment] 2023-07-12 13:17
Hey !
I have this problem too, I'm using 3.5.0 version of nestjs-cls and 10.0.5 version of @nestjs/core

**Comment by Papooch** [comment] 2023-07-12 13:21
@AvnerMaster are you using the nestjs-cls library directly in your app, or through a linked library?

**Comment by AvnerMaster** [comment] 2023-07-12 13:22
Directly, it is a dependency in my package.json

**Comment by Papooch** [comment] 2023-07-12 14:15
@AvnerMaster 
I just tried with a fresh installation of Nest `10.0.5` and `nestjs-cls` `3.5.0` and did not notice any issues. Could you provide a repository where this error is reproduced?

My other guess would be that your `@nestjs/*` dependencies are not properly matched.

For the record, it is working with these versions:
```json
"@nestjs/common": "^10.0.5",
"@nestjs/core": "^10.0.5",
"@nestjs/platform-express": "^10.0.5",
"nestjs-cls": "^3.5.0",
```

**Comment by Papooch** [comment] 2023-07-12 14:37
The error seems very similar to [this one](https://stackoverflow.com/questions/71210888/nestjs-servestaticmodule-nest-cant-resolve-dependencies-of-the-servestaticmodu) and [this one](https://stackoverflow.com/questions/74655072/nestjs-graphql-nest-cant-resolve-dependencies-of-the-graphqlmodule-httpadapt). In both cases, the error is most likely caused by mismatched versions of `@nestjs/common` and `@nestjs/core` or by having some libraries locally linked.

It does not seem to be related to `nestjs-cls`.

**Comment by AvnerMaster** [comment] 2023-07-13 08:13
You are right, I had other libraries that were linked. I managed to fix it by changing the nestjs libraries versions to match my linked libraries nestjs libraries versions. Thank you

**Comment by Papooch** [comment] 2023-07-13 09:26
I'm glad it's resolved. I'm going to assume that a solution to OP's problem is also similar to yours and close this issue.

**Closed by Papooch** 2023-07-13 09:26 UTC
Labels: investigation, needs info
