### ISSUE TITLE
Can't use clsService across different test runs with `--runInBand`

### ISSUE THREAD

**Issue by lazaroofarrill** [Papooch/nestjs-cls#49] opened 2022-12-19 00:57 UTC
I'm using a common setup function for all my unit tests. However when running several test suites together only the first one to use the ClsService succeeds.
Repro url: https://github.com/lazaroofarrill/nestjs-cls-error-across-multiple-test-runs

**Comment by Papooch** [comment] 2022-12-19 07:10
Hm, I was able to reproduce it. I suspect there's something strange happening with how Jest treats async_hooks, because the error only happens with the `--runInBand` flag set. Without it, it works okay.

Given you're only concerned with unit tests that don't need to run in band, this should be enough of a "workaround" for you, but I'll investigate further.

**Comment by lazaroofarrill** [comment] 2022-12-19 08:15
This is truly I sad. I was using a custom it function to wrap run but I really wanted to avoid that. I have to run the tests in band otherwise the crash my computer.

**Comment by Papooch** [comment] 2022-12-19 09:41
I mean, in unit tests, you should treat ClsService as an external dependency and mock it out anyway. E2E tests should also work fine, since the request goes through the middleware. If need be, a custom `it` function seems like a viable workaround.

I have to close this though, because there's nothing I can do about it. Maybe try mocha as your test runner?

**Closed by Papooch** 2022-12-19 09:41 UTC
Labels: external bug
