### ISSUE TITLE
Middleware fails on path excluded from the global prefix

### ISSUE THREAD

**Issue by murbanowicz** [Papooch/nestjs-cls#93] opened 2023-12-13 09:39 UTC
Hi,
I hit weird issue with this great library.
I have a global prefix on my service declared like this:
```
  app.setGlobalPrefix('orders', {
    exclude: [
      'readiness',
      'liveness',
      'dapr/subscribe',
      '(.*)subscription(.*)',
    ],
  });
```

The issue is about the middleware not working **for paths excluded from global prefix**. 

No idea why to be honest.

**Comment by Papooch** [comment] 2023-12-13 20:28
This is most likely an issue with Nest itself than with this library. Maybe also related to this: https://github.com/Papooch/nestjs-cls/issues/92 ?

The library is only mounting the middleware to `*` by default and then Nest does with it what it wants.
What you can do to try and fix it on your end is [mount the middleware manually](https://papooch.github.io/nestjs-cls/setting-up-cls-context/using-a-middleware#manually) for specific routes.

---

However, I'd like to speak from experiance and say that I never had a good time with setting things globally and then _excluding_ some of the things. It makes for less readable code, because you have to always check if that particular thing is excluded or not and you're not always sure _where_ to look for this information.

So I now never use global prefix (unless it is `api` and there are no exceptions) and instead just either repeat it in on the top of each controller (while re-using a constant, of course - e.g. ``Controller(`${GLOBAL_PATH}`/users)``. This gives you the possibility to _explicitly_ opt-out of the global prefix while keeping the information localized where it is used, instead of hiding it in some configuration file somewhere else. Another alternative is using the `RouterModule` to create a hieararchy of controllers - which is what I would probably advise in your situation so you don't have to change your controllers.

**Comment by Papooch** [comment] 2023-12-19 21:35
@murbanowicz Hi, have you investigated this further or did my response help you move forward?

**Comment by Papooch** [comment] 2024-01-17 13:36
I am assuming the issue is either solved or not relevant. Closing.

**Closed by Papooch** 2024-01-17 13:36 UTC
Labels: investigation
