### ISSUE TITLE
Proxied object has function type instead of object type

### ISSUE THREAD

**Issue by Patton-L** [Papooch/nestjs-cls#82] opened 2023-08-15 22:23 UTC
Proxy is defined as `()=>null` at https://github.com/Papooch/nestjs-cls/blob/main/packages/core/src/lib/proxy-provider/proxy-provider-manager.ts#L95C20-L95C25

Is there a specific reason for doing that instead of defining it as an empty object? It's causing object retrieved from cls has `typeof proxiedObject` equal to function instead of object.

**Comment by Papooch** [comment] 2023-08-16 09:34
Hm, if I remember correctly, there was some issue with proxying functions instead of objects. If I remember correctly, JavaScript then complained, that the object's signature doesn't implement the `[Symbol.call]` method or something, so that's why I used a function as the "target", which has all features of objects in addition to being callable.

The problem is, that we don't know the actual type _before_ creating the proxy. It ts created at bootstrap, but the instance it proxies to is created on each request anew.

Can you tell me what your use-case is? I will try to revisit if there's some way to get around this.

**Comment by Papooch** [comment] 2023-08-16 13:52
I see, hmm. Your options are currently:
* either wrapping the data source inside another proxy provider, rather than making a proxy provider out of itself,
* or using "raw" `cls.get(...)`.

I'll try to think of some other way in the new version and add this information to the documentation.

**Comment by Papooch** [comment] 2024-01-19 08:47
A fix has been merged and will be released in a future version (`v4`) together with other breaking changes and features.

**Closed** 2024-01-22 17:20 UTC
Labels: bug
